apiVersion: v1
kind: Service
metadata:
  name: ad-creative-service
spec:
  type: LoadBalancer
  selector:
    app: ad-creative-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
